# CREATE A IMAGE BASE ON NODE
FROM node:latest

# STABLISHING WORKDIRECTORY IN /APP
WORKDIR /app

# COPY PACKAGE.JSON AND PACKAGE-LOCK.JSON TO WORKSPACE
COPY package*.json ./

# INSTALL PROJECT DEPENDECIES
RUN npm install

# COPY APP TO WORKSPACE
COPY . /app

# EXPOSE PORT 3000
EXPOSE 3000

# EXPOSE PORT 8000
EXPOSE 8000

# Start App
CMD npm start